<?php

use Phalcon\Tag;

?>

<!DOCTYPE html>
	<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Create Robot</title>
		<link rel="stylesheet" href="">
	</head>
	<body>
		<?php echo Tag::Form(array('store')); ?>
		<label for="name">Robots Name: </label>
		<?php
		echo Tag::textfield('name');
		echo Mytags::audioField('test');
		?>

		<input type="submit">
	</form>
	</body>
</html>
